variables:
  CODECOV_TOKEN: 4ebf45ff-904a-4a74-aa03-d9fba26cc145

tests:
  image: fluiddyn/python3-stable:lastest
  script:
    - cp site.cfg.default site.cfg
    - python -m venv venv
    - source venv/bin/activate
    - pip install -U pip nox
    - nox -s tests-cov


tests_pythran_mpi:
  image: fluiddyn/python3-stable:lastest
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -U pip nox
    - nox -s tests-full
