variables:
  CODECOV_TOKEN: 4ebf45ff-904a-4a74-aa03-d9fba26cc145

tests:
  image: fluiddyn/python3-stable:lastest
  script:
    - cp site.cfg.default site.cfg
    - pip install -U tox --user
    - tox -e py38,codecov

tests_pythran_mpi:
  image: fluiddyn/python3-stable:lastest
  script:
    - pip install -U tox --user
    - tox -vv -e py38-pythran-mpi,codecov
