
channels:
  - conda-forge

dependencies:
  - python=3.9
  - blas=*=openblas
  - numpy
  - cython
  - pythran
  - h5py
  - matplotlib
  - pandas
  - pyfftw
  - psutil
  - colorlog
  - mako
  - openmpi
  - pip:
    - fluiddyn
    - mpi4py
