# Issues pixi
# - should be able to read pyproject.toml [project] (name, version, description)
# - automatically adds too strict version, bad for Python library
# - optional dependencies and dev groups as PDM
# - import data from pyproject.toml: [project] and [project.optional-dependencies]

[project]
name = "fluidsim"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[tasks]
# use as `pixi run install-editable`
install-dependencies = "pixi install && pip install -e plugins/fluidfft-builder"
install-editable = {cmd = "pip install -e . -v --no-build-isolation --no-deps", depends_on = ["install-dependencies"]}
install-fftw = "pip install -e plugins/fluidfft-fftw --no-build-isolation -v"
install-mpi_with_fftw = "pip install -e plugins/fluidfft-mpi_with_fftw --no-build-isolation -v"
install-fftwmpi = "pip install -e plugins/fluidfft-fftwmpi --no-build-isolation -v"

[dependencies]
python = ">=3.9,<3.11"
numpy = ">=1.26.3"
transonic = ">=0.6.1,<0.7"
fluiddyn = ">=0.5.2"
fluidsim-core = ">=0.7.4"
h5netcdf = ">=1.3.0"
h5py = ">=3.10.0"
xarray = ">=2023.12.0"
matplotlib = ">=3.3"
scipy = ">=1.11.4"
rich = ">=13.7.0"
pip = ">=23.3.2"
pytest = ">=7.4.4"
ipython = ">=8.20.0"
coverage = ">=7.4.0"
pytest-cov = ">=4.1.0"
pytest-mock = ">=3.12.0"
ninja = ">=1.11.1,<1.12"
meson = ">=1.3.1,<1.4"
meson-python = ">=0.15.0,<0.16"
cython = ">=3.0.8,<3.1"
fftw = ">=3.3.10,<3.4"
pkg-config = ">=0.29.2,<0.30"
pyfftw = ">=0.13.1,<0.14"

[pypi-dependencies]
pymech = "*"
pytest-allclose = "*"
importlib-metadata = "*"

[build-dependencies]
meson-python = ">=0.15.0"
pythran = ">=0.15.0"
transonic = ">=0.6.1"
