# Refer: PEP 508, 517, 518 specifications.
# Requires pip>=10
[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools", "wheel",
    "numpy", "Cython",
    # Will only work when Mako supplies wheels / pip supports
    # installation from source
    # "Mako",
    "Jinja2"
]
