# Refer: PEP 508, 517, 518 specifications.
# Requires pip>=10
[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools", "wheel",
    "numpy", "Cython",  # "Mako",  # -> Bug with pip 10?
]
