name: CI Pixi

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["windows-2022", "macos-latest"]
        # python-version: ["3.9", "3.10", "3.11"]
        os: ["windows-2022"]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: prefix-dev/setup-pixi@v0.4.1
      with:
        pixi-version: v0.11.1
        cache: false
    - name: Tests
      run: |
        pixi run install-editable
        pixi run pip install plugins/fluidfft-fftw -v --no-build-isolation --no-deps
    - name: Show meson-log.txt
      if: always()
      run: |
        cat build/cp310/meson-logs/meson-log.txt
        cat 'D:\a\fluidfft\fluidfft\.pixi\env\Scripts\transonic-get-include'
    - name: Tests
      run: |
        pixi run pytest -v tests plugins/fluidfft-fftw
